config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'posts#index'
  resources :users do
    get :autocomplete_user_name, :on => :collection
    member do
      get 'follow_unfollow'
      get 'change_password'
      post 'change_password_method'
      get 'update_profile'
      post 'update_profile_method'
    end
    collection do
      get 'follow'
      post 'login'
      get 'signin'
      get 'logout'
      get 'followers'
      get 'followings'
      get 'favourite_show'
      get 'new_messages'
      post 'messages'
      post 'search_user'
    end
  end
  resources :posts, except: [:new] do
    member do
      get 'post_vote_up'
      get 'post_vote_down'
      get 'favourite'
      get 'read_comments'
    end
    collection do
       post 'user_profile_refresh'
       post 'user_follow_refresh'
    end
    resources :comments, only: [:create]
  end
  resources :profiles,except:[:index] do
    member do
      get 'edit_address'
      get 'edit_company'
      get 'update_address'
      get 'update_company'
    end
    collection do
      get 'address'
      post 'create_address'
      get 'company'
      post 'create_company'
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user
  validates :name, :lastName, :dob, :mobile, presence: true
  # user images
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default.jpg"

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to  update_profile_user_path(current_user)
    else
      render 'edit'
    end
  end


  private

  def profile_params
    params.require(:profile).permit(:name, :lastName, :dob, :gender, :mobile, :image)
  end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/__profile.html.erb
<%= form_for @profile, :html => { :multipart => true } do |s| %>
  <table>
      <tr>
        <td><%=s.label :Name%></td>
        <td><%=s.text_field :name, class: "form-control"%></td>
      </tr>
      <tr>
        <td><%=s.label :LastName%></td>
        <td><%=s.text_field :lastName, class: "form-control"%></td>
      </tr>
        <tr>
          <td><%=s.label :Date_Of_Birth%></td>
          <td><%=s.date_field :dob, class: "form-control"%></td>
        </tr>
        <tr>
          <td><%=s.label :Gender%></td>
          <td><%=s.label 'Male'%><%= s.radio_button 'gender', true%>
              <%=s.label 'Female'%><%= s.radio_button 'gender', false%>
          </td>
        </tr>
        <tr>
          <td><%=s.label :Mobile%></td>
          <td><%=s.text_field :mobile, class: "form-control"%></td>
        </tr>
        <tr>
          <td><%=s.label :Image%></td>
          <td><%=s.file_field :image, class: "form-control"%></td>
        </tr>
        <tr>
          <td></td>
          <td colspan="2"><%= s.submit class:"btn btn-lg btn-primary btn-block"%></td>
      </tr>
  </table>
<% end %>

app/views/profiles/_employ_information.html.erb
  <%= form_for @company, url: create_company_profiles_path, method: :post do |f| %>
    <table>
      <tr>
        <td>Company Name</td>
        <td> <%= f.text_field :name%></td>
      </tr>
      <tr>
        <td>Company Location</td>
        <td> <%= f.text_field :location%></td>
      </tr>

      <tr>
        <td>Designation</td>
        <td> <%= f.text_field :designation%></td>
      </tr>
      <tr>
        <td>Experience</td>
        <td> <%= f.text_field :year%> <%= f.text_field :month%></td>
      </tr>
      <tr>
        <td></td>
        <td colspan="2"><%= f.submit %></td>
      </tr>
    </table>
  <% end %>

app/views/profiles/_user_address.html.erb
<%= form_for @address, url: create_address_profiles_path, method: :post do |f| %>
  <table>
    <tr>
      <td>
        Address 1
      </td>
      <td>
        <%= f.text_area :first_address%>
      </td>
    </tr>
    <tr>
      <td>
        Address 2
      </td>
      <td>
        <%= f.text_area :second_address%>
      </td>
    </tr>
    <tr>
      <td>
        Country
      </td>
      <td>
        <%= f.text_field :country%>
      </td>
    </tr>
    <tr>
      <td>
        State
      </td>
      <td>
        <%= f.text_field :state%>
      </td>
    </tr>
    <tr>
      <td>
        City
      </td>
      <td>
        <%= f.text_field :city%>
      </td>
    </tr>
    <tr>
      <td>
        Zip
      </td>
      <td>
        <%= f.text_field :zipcode%>
      </td>
    </tr>
    <tr>
        <td></td>
        <td colspan="2"><%= f.submit %></td>
    </tr>
  </table>
<% end %>

app/views/profiles/address.html.erb
<%= render 'user_address'%>

app/views/profiles/company.html.erb
<%= render 'employ_information'%>

app/views/profiles/edit.html.erb
<%= render '_profile'%>

app/views/profiles/edit_address.html.erb
<%= @address.blank? %>
<%= render 'user_address'%>

app/views/profiles/edit_company.html.erb
 <%= render partial: "employ_information"%>

app/views/profiles/new.html.erb
<%= render '_profile'%>