config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'posts#index'
  resources :users do
    get :autocomplete_user_name, :on => :collection
    member do
      get 'follow_unfollow'
      get 'change_password'
      post 'change_password_method'
      get 'update_profile'
      post 'update_profile_method'
    end
    collection do
      get 'follow'
      post 'login'
      get 'signin'
      get 'logout'
      get 'followers'
      get 'followings'
      get 'favourite_show'
      get 'new_messages'
      post 'messages'
      post 'search_user'
    end
  end
  resources :posts, except: [:new] do
    member do
      get 'post_vote_up'
      get 'post_vote_down'
      get 'favourite'
      get 'read_comments'
    end
    collection do
       post 'user_profile_refresh'
       post 'user_follow_refresh'
    end
    resources :comments, only: [:create]
  end
  resources :profiles,except:[:index] do
    member do
      get 'edit_address'
      get 'edit_company'
      get 'update_address'
      get 'update_company'
    end
    collection do
      get 'address'
      post 'create_address'
      get 'company'
      post 'create_company'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessor :password_confirmation

  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_confirmation_of :password

  # association with user profile
  has_one :profile
  has_one :address
  has_many :pasts_companies
  # users posts
  has_many :posts
  #users comments
  has_many :comments
  # This association for user folowers
  has_many :users_followings, foreign_key: :follower_id

  # This association for Users Followers
  has_many :user_followers, class_name: :UsersFollowing, foreign_key: :following_id
  has_many :followers, through: :user_followers
  # This association for User Followings
  has_many :user_followings, class_name: :UsersFollowing, foreign_key: :follower_id
  has_many :followings, through: :user_followings
  #This association for show favouirtes user post
  has_many :favourites
  has_many :favshow, class_name: "Post", foreign_key: :post_id
  has_many :favshow, through: :favouirteshow
  accepts_nested_attributes_for :profile
  has_many :messages, foreign_key: :from

  # Get all post that show in current_user page
  def self.get_all_post(follow)
    Post.where(user_id: follow).order('id DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]
  autocomplete :user, :name
  before_action :authenticate_user!, except: [:create, :login, :new, :signin]

  def index
    @users = User.all
    @users_id = current_user.users_followings.pluck(:follower_id)
  end
#show user profile
def show
  @posts = @user.posts
  @post = Post.new
  @check_fav = @user.favourites.pluck(:post_id)
  users = @user_name.followings.pluck(:id)
  users << @user_name[:id]
  @tweets = @user_name.posts.count
  @followings_count = @user.followings.count
  @followings = @user.followings.last(5)
  @follows = User.where("id NOT IN (?)", users).first(5)
  @followers = @user.followers.last(5)
end

#update profile information
  def update_profile
    if current_user.profile.present?
      @profile = current_user.profile
    else
     @profile = current_user.profile
    end
  end

  def update_profile_method
    respond_to do |format|
      if current_user.profile.present?
        if current_user.profile.update(profile_param)
          format.html { redirect_to posts_path, notice: 'Profile was successfully updated.' }
        else
          format.html { render :'update_profile' }
        end
      else
        @profile = current_user.build_profile(profile_param)
        @profile.save
        format.html { redirect_to posts_path, notice: 'Profile was successfully updated.' }
      end
    end
  end

  def search_user
   @users = User.where("name like ?", "%#{params[:data]}%")
    respond_to do |format |
      format.js
    end

  end
  # use for signin page
  def signin
  end
  #use for login
  def login
  	user = User.where("email = (?)",params[:email])
  	if user.exists?
      if user.first.password == params[:password]
        session[:id] = user.first.id
        flash[:notice] = "You are loged in"
        redirect_to posts_path
      else
        redirect_to signin_users_path, notice: 'email_id or password mismatch'
      end
    else
  		redirect_to signin_users_path, notice: 'email_id or password mismatch'
  	end
  end
  # use for Logout
  def logout
    session[:id] = ''
    flash[:notice] = "You are loged out"
    redirect_to signin_users_path

  end
  #show followings users
  def follow
    @users = User.all
    @users_id = current_user.user_followings.pluck(:following_id)
  end

  #show all user for followings
  def follow_unfollow
    @follower = current_user.user_followings.where("following_id = (?)", params[:id])
    if @follower.exists?
      u = UsersFollowing.where("follower_id = (?) and following_id = (?)", current_user[:id], params[:id])
      u.delete_all
      redirect_to follow_users_path
    else
      @users_id = current_user.user_followings.build(following_id: params[:id])
        if @users_id.save
           redirect_to follow_users_path
        else
          redirect_to follow_users_path
        end
    end
  end

  def autocomplete_user_name
    term = params[:term]
    brand_id = params[:brand_id]
    country = params[:country]
    users = User.where('name LIKE ?',"%#{term}%").order(:name).all
    render :json => users.map { |user| {:id => user.id, :label => user.name, :value => user.name} }
  end
  #show all user follower
  def followers
    @followers = current_user.followers
  end
  #show all users followings
  def followings
    @followings = current_user.followings
  end

  #show all user favourites post
  def favourite_show
    @favourites = current_user.favourites.pluck(:post_id)
    @posts = Post.where(id: @favourites)
    # TODO check it
  end
  #show users all private message
  def new_messages
    @users = User.all
    @message = Message.new
    @messages = Message.where(to: current_user.id)
  end

  #this method create user message
  def messages
    u = User.find_by_email(params[:message][:to]).id
    params[:message][:to] = u
    p = params.require(:message).permit(:to, :text)
    @message = current_user.messages.build(p)
    if @message.save
      respond_to do |format|
        format.js
      end
    end
 end

  #show change user password
  def change_password
    @profile = current_user
  end

  # change user password
  def change_password_method
    respond_to do |format|
      if current_user.update(email: params[:email], password: params[:password])
        format.js
        format.html { redirect_to posts_path, notice: 'Password was successfully updated.' }
      else
        format.html { redirect_to change_password_user_path, notice: 'Password was not successfully updated.' }
      end
    end
  end

  # find user

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_count
    @tweet = User.find(params[:id]).posts.count
    @followings = User.find(params[:id]).followings.count
    @followers = User.find(params[:id]).followers.count
    @favourites = User.find(params[:id]).favourites.count
    return @tweet, @followers, @followings, @favourites
  end
end

app/views/users/_form.html.erb
<div class='page-header'>
  <h1> Create Your New Account </h1>
</div>
<%=form_for (@user),class:"form-signin", :html => { :multipart => true } do |f| %>
	<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	<table>
		<tr>
			<td><%=f.label :Name%></td>
			<td><%=f.text_field :name, class: "form-control"%></td>
		</tr>
    <tr>
      <td><%=f.label :Email%></td>
      <td><%=f.email_field :email, class: "form-control"%></td>
    </tr>
    <tr>
      <td><%=f.label :Password%></td>
      <td><%=f.password_field :password, class: "form-control"%></td>
    </tr>
    <tr>
      <td><%=f.label :Conform_Password%></td>
      <td><%=f.password_field :password, class: "form-control"%></td>
    </tr>
    <%= f.fields_for :profile, :html => { :multipart => true } do |s| %>
      <tr>
      <td><%=s.label :LastName%></td>
      <td><%=s.text_field :lastName, class: "form-control"%></td>
    </tr>
      <tr>
        <td><%=s.label :Date_Of_Birth%></td>
        <td><%=s.date_field :dob, class: "form-control"%></td>
      </tr>
      <tr>
        <td><%=s.label :Gender%></td>
        <td><%=s.label :Male%><%= s.radio_button 'gender', 'male'%>
            <%=s.label 'Female'%><%= s.radio_button 'gender', 'female'%>
        </td>
      </tr>
      <tr>
        <td><%=s.label :Country%></td>
        <td><%=s.text_field :country, class: "form-control"%></td>
      </tr>
      <tr>
        <td><%=s.label :Zip%></td>
        <td><%=s.text_field :zip,class: "form-control"%></td>
      </tr>
      <tr>
        <td><%=s.label :Mobile%></td>
        <td><%=s.text_field :mobile, class: "form-control"%></td>
      </tr>
      <tr>
        <td><%=s.label :Image%></td>
        <td><%=s.file_field :image, class: "form-control"%></td>
      </tr>
    <% end %>
    <tr>
        <td></td>
        <td colspan="2"><%=f.submit class:"btn btn-lg btn-primary btn-block"%></td>
    </tr>
  </table>
<% end %>

app/views/users/change_password.html.erb
<div class="wrapper">
  <%=form_tag change_password_method_user_path,id: 'formchangepassword', class:"form-signin", method: :post do %>
     <h2 class="form-signin-heading">Password here</h2>
    <table>
      <tr>
        <td><%=email_field_tag :email, @profile.email, class: "form-control", placeholder: "Email"%></td>
      </tr>
      <tr>
        <td><%=password_field_tag :password,nil, class: "form-control", placeholder: "Password"%></td>
      </tr>
      <tr>
        <td><%=password_field_tag :password,nil, class: "form-control", placeholder: "Confirm Password"%></td>
      </tr>
      <tr>
        <td><%=submit_tag 'change', class:"btn btn-lg btn-primary btn-block", id: 'changepassword'%></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/users/change_password_method.js.erb
document.write("Password changed!");

app/views/users/edit.html.erb
<%= render 'change_password'%>

app/views/users/follow.html.erb
<div class='page-header'>
  <h1> Suggestion for Followers </h1>
</div>
<div class='col-sm-offset-2 col-sm-8'>
  <table class="table">
    <% @users.each do |user| %>
      <%if user.id ==current_user[:id]%>
      <% else %>
      <tr>
          <% if user.profile.present? %>
            <td><%= image_tag user.profile.image.url, size: "60x40" %></td>
          <% else %>
            <td><%= image_tag "default.jpg", size: "60x40" %></td>
          <% end %>
          <td><%= user.profile.name %></td>
          <%if user.id.present? %>
            <% if @users_id.include?(user.id) %>
              <td><%= link_to 'Added', follow_unfollow_user_path(user.id), class: "btn btn-default-sm", id: user.id %></td></td>
            <% else %>
                <td> <%= link_to 'follow', follow_unfollow_user_path(user.id), class: "btn btn-default-sm", id: user.id %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<%=render 'form'%>

app/views/users/new_messages.html.erb
<div class='page-header'>
  <h1> Your Meassages.... </h1>
</div>
<%= form_for(@message, url: messages_users_path) do |f|%>
    <table>

        <tr><td>
          <%=f.select :to, options_for_select(@users.collect{ |u| [u.email, u.email] })%>

        </td></tr>
        <tr><td><%=f.text_area :text, class: "form-control", placeholder: "Message",:cols => 30, :rows => 5 %></td></tr><br>
        <tr><td ><%=f.submit 'Send', class: "btn btn-default btn-sm",id: 'message', style: "width: 100px;"%></td></tr>
    </table>
<% end %>
<br><br>
<% @messages.each do |m|%>
  <div>
    <%=User.find(m.from).name%>->&nbsp;&nbsp;&nbsp;&nbsp;<%=m.text %>

  </div>
<%end%>

app/views/users/search_user.js.erb
<ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="search_users" style="min-width: 127px;">
  <%@users.each do |user|%>
     <li role="presentation"><%= link_to user.name, user_path(user), class: "btn btn-default-lg navbar-btn" %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<style type="text/css">
html body{
  background-image: none;
  background-color: white;
}
</style>
<div class="ProfileCanopy">
  <div class="ProfileCanopy-inner">
    <div class="ProfileCanopy-header u-bgUserColor">
      <div class="AppContainer">
        <div class="ProfileCanopy-avatar">
          <div class="ProfileAvatar">
            <div>
              <%=image_tag @user.profile.image, size: "185x188", style: "border-radius: 5px;" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="ProfileCanopy-navBar">
      <div class="AppContainer">
        <div class="Grid Grid--withGutter">
          <div class="Grid-cell u-size1of3 u-lg-size1of4"></div>
          <div class="Grid-cell u-size2of3 u-lg-size3of4">
            <div class="container-fluid navshift">
              <ul class="nav navbar-nav container">
                <% x, y, z, a = show_count%>
                <li> <%=link_to '#', class: "u-textCenter" do %>
                      <span class="ProfileNav-label">Tweet</span>
                      <span class="ProfileNav-value"> <%= x%></span>
                    <% end %>
                </li>
                <li> <%=link_to '#',class: "u-textCenter"  do %>
                      <span class="ProfileNav-label">Photos/Videos</span>
                      <span class="ProfileNav-value"> <%= z%></span>
                    <% end %>
                </li>
                <li> <%=link_to '#', class: "u-textCenter"  do %>
                      <span class="ProfileNav-label">Followers</span>
                      <span class="ProfileNav-value"> <%= y%></span>
                    <% end %>
                </li>
                <li> <%=link_to '#',class: "u-textCenter"  do %>
                      <span class="ProfileNav-label">Followings</span>
                      <span class="ProfileNav-value"> <%= z%></span>
                    <% end %>
                </li>
                <li> <%=link_to '#',class: "u-textCenter"  do %>
                      <span class="ProfileNav-label">Favorites</span>
                      <span class="ProfileNav-value"> <%= a%></span>
                    <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="display: inline">
  <div style="float:left; display: block">
  </div>
  <div class="show_user_post">
    <%=render partial: "posts/post", collection: @posts%>
  </div>
  <div class="show_follower">
    bdfjhdsbfgkjshihislk
  </div>
</div>

app/views/users/signin.html.erb
<div class="wrapper">
	<%= form_tag login_users_path, class:"form-signin", method: :post do %>
		 <h2 class="form-signin-heading">Please login</h2>
		<table>
			<tr>
				<td><%=email_field_tag :email,nil, class: "form-control", placeholder: "Email Address"%></td>
			</tr>
			<tr>
				<td><%=password_field_tag :password,nil, class: "form-control", placeholder: "Password"%></td>
			</tr>
			<tr>
				<td><%=submit_tag 'login', class:"btn btn-lg btn-primary btn-block"%></td>
			</tr>
		</table>
	<% end %>
</div>

app/views/users/update_profile.html.erb
<h3>Update Your Informations</h3>

<%= link_to "Profile",  edit_profile_path(current_user)%>
<%= link_to "Address",  edit_address_profile_path(current_user)%>
<%= link_to "Previous Company",  edit_company_profile_path(current_user)%>