config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'posts#index'
  resources :users do
    get :autocomplete_user_name, :on => :collection
    member do
      get 'follow_unfollow'
      get 'change_password'
      post 'change_password_method'
      get 'update_profile'
      post 'update_profile_method'
    end
    collection do
      get 'follow'
      post 'login'
      get 'signin'
      get 'logout'
      get 'followers'
      get 'followings'
      get 'favourite_show'
      get 'new_messages'
      post 'messages'
      post 'search_user'
    end
  end
  resources :posts, except: [:new] do
    member do
      get 'post_vote_up'
      get 'post_vote_down'
      get 'favourite'
      get 'read_comments'
    end
    collection do
       post 'user_profile_refresh'
       post 'user_follow_refresh'
    end
    resources :comments, only: [:create]
  end
  resources :profiles,except:[:index] do
    member do
      get 'edit_address'
      get 'edit_company'
      get 'update_address'
      get 'update_company'
    end
    collection do
      get 'address'
      post 'create_address'
      get 'company'
      post 'create_company'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	#show all users post that folloing by current user
	def index
		@post = Post.new
		@followings_count = current_user.followings.count
		@followings = current_user.followings.last(5)
		@followers = current_user.followers.last(5)
	end

	#create new post
	def create
		@post = current_user.posts.build(params_post)
		@check_fav = current_user.favourites.pluck(:post_id)
		@user_name = current_user
		respond_to do |format|
			if @post.save
				format.js
				#redirect_to posts_path
			else
				render 'new'
			end
		end
	end
	#show your post and create comment
	def show

	end
	#update your posts
	def update
		respond_to do |format|
      if @post.update(params_post)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
	end

	#destroy your post
	def destroy
		if @post.destroy
			redirect_to posts_path, notice: 'Post was sucessfuly destroy..'
		else
			redirect_to posts_path, error: 'Post not deleted'
		end
	end
	#Increase Post vote
	def post_vote_up
		@post = Post.find(params[:id])
		respond_to do |format|
			@post.vote = @post.vote + 1
			@post.save
			format.js
		end
	end
  #decrease Post vote
	def post_vote_down
		@post = Post.find(params[:id])
		respond_to do |format|
			@post.vote = @post.vote - 1
			@post.save
			format.js
		end
	end
	#refresh user profile in post index page
	def user_profile_refresh
			@followings = current_user.followings.last(5)
			respond_to do |format|
				format.js
			end
	end

	def user_follow_refresh
		users = current_user.followings.pluck(:id)
		users << current_user[:id]
		@follows = User.where("id NOT IN (?)", users).first(5)
			respond_to do |format|
				format.js
			end
	end
	#use for favourites post
	def favourite
		@favourite_check = current_user.favourites.where("user_id = ? and post_id = ? ",current_user.id, params[:id])
		@favourite = current_user.favourites.build(post_id: params[:id])
		respond_to do |format|
			if @favourite_check.exists?
				@favourite_check.delete_all
				format.js
			else
				@favourite.save
				format.js
			end
		end
	end

	def read_comments
		@comments = Post.find(params[:id]).comments
		respond_to do |format|
			format.js
		end
	end
	private
	#find post by id
	def set_post
		@post = Post.find(params[:id])
	end
	#this function use for permission for new post
	def params_post
		params.require(:post).permit(:title)
	end

end

app/helpers/posts_helper.rb
module PostsHelper

  def favourit?
    current_user.favourites.pluck(:post_id)
  end
end

app/views/posts/_form.html.erb
<br>
<%=form_for (@post) do |f|%>
  <%=f.label 'Post'%>
  <%=f.text_area 'title' %><br>
  <%=f.submit class: "btn btn-primary btn-sm"%>
 <%end%>

app/views/posts/_post.html.erb
<div class="headeinnerdiv" id="div-<%=post.id%>">
  <div style="height: auto; width:100%;">
    <div style=" float:left;min-height: 60px; width:10%;">
      <%=link_to user_path(current_user) do %>
        <% if post.user.profile.present? %>
          <%= image_tag post.user.profile.image.url, size: "48x48",class:"avatarImagediv",style:"" %>
        <% else %>
          <%= image_tag "default.jpg", size: "48x48", class:"avatarImagediv",style:"" %>
        <% end %>
       <% end %>
    </div>
    <div style=" float:right;min-height: 60px; width:90%;">
      <span><%=link_to post.user.profile.name.upcase, user_path(current_user), class: "fullname", style: ""%></span>
      <p><%=post.title%></p>
    </div>
  </div>
  <div class="navbar-header" id="postinfoexpand<%=post.id%>" style="display:none">
    <ul class="nav navbar-nav container" style="height:60px;">
      <li style="height:60px;">
        <%=link_to read_comments_post_path(post) ,class: 'read_comment', style: "height:60px;" do %>
          <p>comments</p>
          <strong><%= post.comments.count %></strong>
        <% end %>
      </li>
      <li style="height:60px;">
        <%=link_to post_path(post), style: "height:60px;" do %>
          <p>Favourites</p>
          <strong><%= post.favourites.count%></strong>
        <% end %>
      </li>
    </ul>
  </div>
  <div style="min-height: auto; width:auto; margin-top:10px;">
    <i class="glyphicon glyphicon-resize-full btn" id="expand<%=post.id%>"></i>
    <ul class="nav nav-pills navbar-right" >
      <li>
        <%if post.user.id == current_user.id%>
           <h5> <%=link_to 'delete', post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' } ,id: "fav#{post.id}"%>
        <% end %>
      </li>
      <li id="favcheck">
        <%if favourit?.present?%>
          <% if favourit?.include?(post.id) %>
            <h5> <%=link_to 'Unfavourite', favourite_post_path(post),id: "fav#{post.id}"%></h5>
          <% else %>
            <h5><%=link_to 'favourite', favourite_post_path(post),id:"fav#{post.id}"%></h5>
          <% end %>
        <% else %>
           <h5><%=link_to 'favourite', favourite_post_path(post),id:"fav#{post.id}"%></h5>
        <% end %>
      </li>

      <li>
        <h5><%= link_to 'comment',"#{post.id}", class:"comment"%></h5>
      </li>
    </ul>
  </div>
</div>

app/views/posts/_read_all_comments.html.erb
<ol class="activity-popup-users comment-dropdown">
  <% comments.each do |comment|%>
    <li >
      <div class="stream-item">
        <div style="float:left; margin-left:5px;"><%= link_to (image_tag comment.post.user.profile.image.url, size: "30x30"), user_path(comment.post.user)%>
        </div>
        <div style= "padding-left: 5px;"> <%=comment.content%></div>
      </div>
    </li><br>
  <% end %>
</ol>

app/views/posts/_userfollowfollowing.html.erb
<div style="float:right;width:21%;margin-right:4%;height:400px;">
  <div class="flex-module">
    <div class="flex-module-header">
      <h3 style="display: inline-block;">Who to follow</h3>
       <%=link_to "Refresh", user_follow_refresh_posts_path, id: "user_follow_refresh"%>
        <%= link_to 'view all', follow_users_path %>
    </div>
    <div id="user_follow_div">
      <% follows.each do |user|%>
        <div id="show_follow_user">
          <table >
            <tr id ="row-<%=user.id%>">
              <td>
                <%=link_to user_path(user) do%>
                  <% if user.profile.present? %>
                    <%= image_tag user.profile.image.url, size: "48x48" %>
                  <% else %>
                    <%= image_tag "default.jpg", size: "48x48" %>
                  <% end %>
                <% end %>
              </td>
              <td class="fullnamefollows" style="padding-left: 10px;" valign="top"><%=link_to user.profile.name.upcase, user_path(user)%> <br><%= link_to 'follow', follow_unfollow_user_path(user), class: "btn btn-default btn-sm", role: "button", id: user.id, style:"width:70px; margin-top:8px;" %></td>
            </tr>
          </table>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_userprofile.html.erb
<div id="yourstatus" style="float:left; margin-left:5%;margin-right:2%; width:20%;"
    class="DashboardProfileCard module">
    <div style="width:100%;height:288px;">`
      <%=link_to image_tag('default_profile_6_bigger.png',:alt =>  "alt text", class:"DashboardProfileCard-avatarImage"),user_path(current_user), class: "DashboardProfileCard-bg u-bgUserColor u-block"%>
      <div class="DashboardProfileCard-userFields ">
        <div class="DashboardProfileCard-name">
          <%=link_to current_user.profile.name, user_path(current_user), class:"textInheritColor"%>
        </div>
        <span>
           <%=link_to current_user.email, user_path(current_user), class:"screennameLink"%>
        </span>
          <div style="width:100%;" class="userprofilestatus ">
            <div class=" col-md-6 ">
              <%=link_to  user_path(current_user), class:"screennameLink", style:"TEXT-DECORATION: NONE", title: " #{@tweets}Tweets" do %>
                <span class="statelable" STYLE="TEXT-DECORATION: NONE">POSTS</span><BR>
                <span STYLE="TEXT-DECORATION: NONE; color: #0084B4 !important;" class="statValue"><%=@tweets%></span>
              <% end %>
            </div>
            <div class="col-md-6">
              <%=link_to  user_path(current_user), class:"screennameLink", style:"TEXT-DECORATION: NONE", title: " #{@followings}Tweets" do %>
                <span class="statelable" STYLE="TEXT-DECORATION: NONE">FOLLOWINGS</span><BR>
                <span STYLE="TEXT-DECORATION: NONE; color: #0084B4 !important;" class="statValue"><%=@followings_count%></span>
              <% end %>
            </div>
          </div>
      </div>
    </div>
    <div>
      <div class="flex-module">
        <div class="flex-module-header">
          <h3 style="display: inline-block;">Followings</h3>
            <%=link_to 'Refresh', user_profile_refresh_posts_path, class: 'btn-link', id:"refresh_followings"%>
            <%= link_to 'view all', followings_users_path %>
        </div>
        <div width:100% id="refreshfollowingsdiv">
            <% @followings.each do |follow|%>
              <ul class="nav nav-pills">
                <li style="padding:0px;">
                  <%=link_to user_path(follow) do %>
                    <% if follow.profile.present? %>
                       <%= image_tag follow.profile.image.url, size: "48x48"%>
                     <% else %>
                      <%= image_tag "default.jpg", size: "48x48" %>
                    <% end %>
                    <span class="fullname"><%=follow.profile.name.upcase%><span>
                  <% end %>
                </li>
              </ul>
            <% end %>
        </div>
      </div>
    </div>

    <div>
      <div class="flex-module">
        <div class="flex-module-header">
          <h3 style="display: inline-block;">Followers</h3>
            <button type= "button" class="btn-link">Refresh</button>
            <%= link_to 'view all',  followers_users_path %>
        </div>
        <div width:100%>
            <% @followers.each do |follow|%>
              <ul class="nav nav-pills">
                <li style="padding:0px;">
                  <%=link_to user_path(follow) do %>
                    <% if follow.profile.present? %>
                       <%= image_tag follow.profile.image.url, size: "48x48"%>
                     <% else %>
                      <%= image_tag "default.jpg", size: "48x48" %>
                    <% end %>
                    <span class="fullname"><%=follow.name.upcase%><span>
                  <% end %>
                </li>
              </ul>
            <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/posts/create.js.erb
$('#allpostshow').prepend("<%= escape_javascript render(partial: 'post', locals: {post: @post }) %>");

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/favourite.js.erb
<%if @favourite_check.exists?%>
  document.getElementById("fav<%=params[:id]%>").innerHTML= 'Unfavourites';
<%else%>
  document.getElementById("fav<%=params[:id]%>").innerHTML= 'favourites';
<%end%>

app/views/posts/index.html.erb
<div id="main">
  <%=render 'userprofile'%>
  <div id="allpost" style="float:left;width:46%;">
    <div class="headeinner">
      <h2>Tweets</h2>
    </div>
    <div id="allpostshow">
    <%=render partial: "post", collection: User.get_all_post(following_users)%>
  </div>
  </div>
    <%=render "userfollowfollowing"%>
</div>

<div class="modal fade" id="post_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="padding-top: 220px;width: 37%;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"> Comment on Tweet</h4>
      </div>
      <div class="modal-body get_comment" contenteditable="true">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary new_comment" data-dismiss="modal">Tweet</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="read_comment_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="padding-top: 220px;width: 37%;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"> Read Comments</h4>
      </div>
      <div class="account">
      <div class="modal-body account" id="show_user_comment">

      </div>
    </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary read_comment_model" data-dismiss="modal">Tweet</button>
      </div> -->
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/post_vote_down.js.erb
var x = <%=@post.vote%>
document.getElementById("<%=@post.id%>").innerHTML= x;

app/views/posts/post_vote_up.js.erb
var x = <%=@post.vote%>
document.getElementById("<%=@post.id%>").innerHTML= x;

app/views/posts/show.html.erb
<br>
  <%= @post.title %><br>
  <input type="button" value="Comment" id="showDiv"><br>
<div class='post' id="div1" style="display: none;">
  <%=form_for([@post, @comment]) do |f|%>
    <%=f.label Comment %>
    <%=f.text_area :content%>
    <br>
    <%=f.submit id: "hideDiv"%>
  <% end %>
</div>
<br>
<div>
  <table class="table table-hover" id="showcomments">
    <% @post.comments.reverse_order.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/posts/user_follow_refresh.js.erb
$('#user_follow_div').replaceWith('<% @follows.each do |user|%><div id="show_follow_user"><table ><tr id ="row-<%=user.id%>"><td><%=link_to user_path(user) do%><% if user.profile.present? %><%= image_tag user.profile.image.url, size: "48x48" %><% else %><%= image_tag "default.jpg", size: "48x48" %><% end %><% end %></td><td class="fullnamefollows" style="padding-left: 10px;" valign="top"><%=link_to user.name.upcase, user_path(user)%> <br><%= link_to 'follow', follow_unfollow_user_path(user), class: "btn btn-default btn-sm", role: "button", id: user.id, style:"width:70px; margin-top:8px;" %></td></tr></table></div><br> <% end %>');