config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'posts#index'
  resources :users do
    get :autocomplete_user_name, :on => :collection
    member do
      get 'follow_unfollow'
      get 'change_password'
      post 'change_password_method'
      get 'update_profile'
      post 'update_profile_method'
    end
    collection do
      get 'follow'
      post 'login'
      get 'signin'
      get 'logout'
      get 'followers'
      get 'followings'
      get 'favourite_show'
      get 'new_messages'
      post 'messages'
      post 'search_user'
    end
  end
  resources :posts, except: [:new] do
    member do
      get 'post_vote_up'
      get 'post_vote_down'
      get 'favourite'
      get 'read_comments'
    end
    collection do
       post 'user_profile_refresh'
       post 'user_follow_refresh'
    end
    resources :comments, only: [:create]
  end
  resources :profiles,except:[:index] do
    member do
      get 'edit_address'
      get 'edit_company'
      get 'update_address'
      get 'update_company'
    end
    collection do
      get 'address'
      post 'create_address'
      get 'company'
      post 'create_company'
    end
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :first_address, :second_address, :country, :state, :city, :zipcode , presence: true
  belongs_to :user
  before_save :change_address
  def change_address
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ActiveRecord::Base
 validates :name, presence: true
 validates :name, uniqueness: true
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :favshow, class_name: 'Post'
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
end

app/models/pasts_company.rb
class PastsCompany < ActiveRecord::Base
  belongs_to :user
  validates :name, :location, :designation, :year, :month , presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user
  validates :name, :lastName, :dob, :mobile, presence: true
  # user images
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default.jpg"

end

app/models/state.rb
class State < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessor :password_confirmation

  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_confirmation_of :password

  # association with user profile
  has_one :profile
  has_one :address
  has_many :pasts_companies
  # users posts
  has_many :posts
  #users comments
  has_many :comments
  # This association for user folowers
  has_many :users_followings, foreign_key: :follower_id

  # This association for Users Followers
  has_many :user_followers, class_name: :UsersFollowing, foreign_key: :following_id
  has_many :followers, through: :user_followers
  # This association for User Followings
  has_many :user_followings, class_name: :UsersFollowing, foreign_key: :follower_id
  has_many :followings, through: :user_followings
  #This association for show favouirtes user post
  has_many :favourites
  has_many :favshow, class_name: "Post", foreign_key: :post_id
  has_many :favshow, through: :favouirteshow
  accepts_nested_attributes_for :profile
  has_many :messages, foreign_key: :from

  # Get all post that show in current_user page
  def self.get_all_post(follow)
    Post.where(user_id: follow).order('id DESC')
  end
end

app/models/users_following.rb
class UsersFollowing < ActiveRecord::Base
  #follower_id, following_id
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_name
    unless current_user.profile.blank?
      current_user.profile.name + " "+ current_user.profile.lastName
    else
      'User'
    end
  end

  def following_users
    current_user.followings.pluck(:id) << (current_user[:id])
  end

  def count_tweet
    current_user.posts.count
  end

  def follows
    User.where("id NOT IN (?)", following_users).first(5)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def favourit?
    current_user.favourites.pluck(:post_id)
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def show_count
    @tweet = User.find(params[:id]).posts.count
    @followings = User.find(params[:id]).followings.count
    @followers = User.find(params[:id]).followers.count
    @favourites = User.find(params[:id]).favourites.count
    return @tweet, @followers, @followings, @favourites
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Users</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "autocomplete-rails.js"%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <div class= 'navbar navbar-default navbar-fixed-top ' style="height:50px;">
        <div style="margin-left: 60%; margin-top:-10px;">
          <ul class="nav navbar-nav container" >
            <li style="margin-top:20px;"><%= autocomplete_field_tag :user_name, "",autocomplete_user_name_users_path %>
            </li>
            <li> <%= link_to 'Post', posts_path, class: "btn btn-default-lg navbar-btn" %></li>
            <li> <%= link_to 'favourite', favourite_show_users_path, class: "btn btn-default-lg navbar-btn" %></li>
            <li class="dropdown home-head">
              <a id="drop4" data-toggle="dropdown" href="#"> Home <span class="caret"></span></a>
                <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4" style="min-width: 127px;">
                  <li role="presentation"><%= link_to current_user_name, user_path(current_user), class: "btn btn-default-lg navbar-btn" %></li>
                  <li role="presentation"><%= link_to "Message",  new_messages_users_path, class: "btn btn-default-lg navbar-btn" %></li>
                  <li role="presentation"><%= link_to "Update Profile",  update_profile_user_path(current_user), class: "btn btn-default-lg navbar-btn" %></li>
                  <li role="presentation"><%= link_to "Change Password",  edit_user_registration_path, class: "btn btn-default-lg navbar-btn" %></li>
                  <li role="presentation" class="divider"></li>
                  <li role="presentation"> <%= link_to 'Sign out',  destroy_user_session_path, :method => :delete, class: "btn btn-default-lg navbar-btn" %></li>
                </ul>
            </li>
            <li style="margin-top:20px;">
              <span  data-toggle="modal" data-target="#myModal"
               id="postButton" title="Compose new tweet"><%= image_tag 'tweet(3).jpg', size: "40x40" %>
              </span>
            </li>
          </ul>
        </div>
      </div>
    <%end%>

    <div class="modal" id="myModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:hidden">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span id="closeModelX" class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel" style="text-align: center;">Compose New Tweet</h4>
          </div>
          <%=form_for (Post.new) do |f|%>
            <div class="modal-body">
              <%=f.text_area :title, style: "width:560px;height:100px;resize: none;"%>
            </div>
            <div class="modal-footer">
              <button type="button"  id ="closeModelB" class="btn btn-default" data-dismiss="modal">Close</button>
              <%=f.submit :Tweet, class:"btn btn-primary", id:"post_new" %>
            </div>
          <%end%>
        </div>
    </div>
</div>
    <div style="padding-top:auto;">
      <% if flash[:notice] %>
        <div class="notice alert alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notice"><%= flash[:alert] %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>